inherit_from: .rubocop_todo.yml

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
  
Lint/RaiseException:
  Enable: true
  
Lint/StructNewOverride:
  Enable: true