# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 36aabe454c05751ec0f2b16fdb5bb008909d0d4bb37f7e010b2cea48ba0f503f87d98711d9ab5ec0c8c92ef51241ee3bc66b29c3edc68ef218e0cdac441d10ec

test:
  secret_key_base: bd1a943bc8b7dcabb7cd26b9593d637ddc8f22d32c03071edd7aaca3496c13520ea1cdf4cde789c310cf23bf7945504e794ec0a3b9191e30790cd10ac14a74c7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
